### ISSUE TITLE
Project page layout

### ISSUE THREAD

**Issue by chriswiesner** [serg/yourfolio#2]
It would be great if you could include a layout template for show-casing a single project. (Project detail page)

**Comment by serg** [comment]
Hello @chriswiesner,

Thank you for your interest to Yourfolio theme!
Yeah, it could be useful to have. This theme was created to be simple as much as possible. In this case I didn't include the ability to define separate pages for the projects. Probably, it could be helpful to add this option and improve the current version of theme. Its needs a time for think of how it should looks. Unfortunately, I couldn't give a promise about how and when it will be done. But I will keep it in list.

Thank you for sharing your idea about enhancement of this theme!

**Comment by MUWalter** [comment]
Hi there, great template! I also would appreciate a small page for a project description with pictures and the ability to implement videos. Unfortunately I don't know how to do that.

**Comment by serg** [comment]
Hello @MUWalter,

Thank you for your feedback about this theme! I very appreciate this action!
I will take this in consideration.

By the way, you could add this feature on your side. For this the creation of layout and styles are needed.
The rough plan is: 
- copy the `layouts/single.html` file into `layouts/projects/single.html` folder. Modify it for your use case.
- add corresponding folder inside `content` with files (e.g. `content/projects/strato.md`).
- add styles for content items (paragraphs, lists, images, videos, etc...) on this layout. Your styles could be merged with `static/app.css` (please [unminify](https://unminify.com/) this file before adding updates).

Hope, it was helpful.
Have a great day!

**Comment by MUWalter** [comment]
> Hello @MUWalter,
> 
> Thank you for your feedback about this theme! I very appreciate this action!
> I will take this in consideration.
> 
> By the way, you could add this feature on your side. For this the creation of layout and styles are needed.
> The rough plan is:
> 
> * copy the `layouts/single.html` file into `layouts/projects/single.html` folder. Modify it for your use case.
> * add corresponding folder inside `content` with files (e.g. `content/projects/strato.md`).
> * add styles for content items (paragraphs, lists, images, videos, etc...) on this layout. Your styles could be merged with `static/app.css` (please [unminify](https://unminify.com/) this file before adding updates).
> 
> Hope, it was helpful.
> Have a great day!

Dear Serg, Thank you very much for your reply! I tried to do it, but somehow it didn't work. Maybe if you have time, you could explain it a little bit more. But once again, thanks for your great work so far!

**Comment by MUWalter** [comment]
Hello,

I tried but I couldn't manage properly. Could you be  a little bit more specific of how to proceed?


All the best
MArk

**Comment by MUWalter** [comment]
> Hello @MUWalter,
> 
> Thank you for your feedback about this theme! I very appreciate this action!
> I will take this in consideration.
> 
> By the way, you could add this feature on your side. For this the creation of layout and styles are needed.
> The rough plan is:
> 
> * copy the `layouts/single.html` file into `layouts/projects/single.html` folder. Modify it for your use case.
> * add corresponding folder inside `content` with files (e.g. `content/projects/strato.md`).
> * add styles for content items (paragraphs, lists, images, videos, etc...) on this layout. Your styles could be merged with `static/app.css` (please [unminify](https://unminify.com/) this file before adding updates).
> 
> Hope, it was helpful.
> Have a great day!

Thank you very much. I managed to implement a project page.

**Comment by chriswiesner** [comment]
@MUWalter would be great if you could share it and do a PR here

**Comment by MUWalter** [comment]
Sure, actually I tried to, but I didn’t understand how this works. It was way easier to do the modifications as Sergey suggested. As soon as I will have time to dig deeper into github, I will post this. But it was really not too difficult.

**Comment by MUWalter** [comment]
The other thing I am struggling with at the moment is a footer for imprint and data privacy. Any ideas how to do this?

**Comment by serg** [comment]
Hello,

@chriswiesner, @MUWalter thanks to all for your comments!
Seems, like this so actual to have layout like for project items, blog posts, etc... I plan to apply more effort on this.
Unfortunately, I haven't time for this at current moment, but it worth for consideration definitely.

@MUWalter regarding to footer. Please see how [header partial](https://github.com/serg/yourfolio/blob/master/layouts/partials/header.html) was implemented and included into [layouts/index.html](https://github.com/serg/yourfolio/blob/master/layouts/index.html) and [layouts/_default/single.html](https://github.com/serg/yourfolio/blob/master/layouts/_default/single.html).

**Comment by MUWalter** [comment]
> Hello @MUWalter,
> Thank you for your feedback about this theme! I very appreciate this action!
> I will take this in consideration.
> 
> By the way, you could add this feature on your side. For this the creation of layout and styles are needed.
> The rough plan is:
> 
> * copy the `layouts/single.html` file into `layouts/projects/single.html` folder. Modify it for your use case.
> * add corresponding folder inside `content` with files (e.g. `content/projects/strato.md`).
> * add styles for content items (paragraphs, lists, images, videos, etc...) on this layout. Your styles could be merged with `static/app.css` (please [unminify](https://unminify.com/) this file before adding updates).
> 
> Hope, it was helpful.
> Have a great day!

Dear @serg, 

there is a bug that really drives me crazy. I have no idea why it occurs. Maybe you can have a look at it. I added the project page "Strato" as you described above. Now when you click at the start page on the Strato picture, you'll get redirected to /projects/strato/ . So far, so good.

Start page
![start](https://user-images.githubusercontent.com/29971407/118396470-f8562980-b64f-11eb-8c33-4eb9c38118ee.png)

Project page
![strato project](https://user-images.githubusercontent.com/29971407/118396514-29365e80-b650-11eb-98bd-0ba66c6edda6.png)

For GDPR reasons I prefer to host the Google fonts myself on my server. I installed the Open Sans webfonts to /static/fonts/ and changed the /themes/yourfolio/assets/scss/_fonts.scss to following using https://google-webfonts-helper.herokuapp.com/fonts/open-sans?subsets=latin

/* open-sans-regular - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/open-sans-v18-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('../fonts/open-sans-v18-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/open-sans-v18-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/open-sans-v18-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('../fonts/open-sans-v18-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/open-sans-v18-latin-regular.svg#OpenSans') format('svg'); /* Legacy iOS */
}
/* open-sans-600 - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 600;
  src: url('../fonts/open-sans-v18-latin-600.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('../fonts/open-sans-v18-latin-600.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/open-sans-v18-latin-600.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/open-sans-v18-latin-600.woff') format('woff'), /* Modern Browsers */
       url('../fonts/open-sans-v18-latin-600.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/open-sans-v18-latin-600.svg#OpenSans') format('svg'); /* Legacy iOS */
}
/* open-sans-700 - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 700;
  src: url('../fonts/open-sans-v18-latin-700.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('../fonts/open-sans-v18-latin-700.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('../fonts/open-sans-v18-latin-700.woff2') format('woff2'), /* Super Modern Browsers */
       url('../fonts/open-sans-v18-latin-700.woff') format('woff'), /* Modern Browsers */
       url('../fonts/open-sans-v18-latin-700.ttf') format('truetype'), /* Safari, Android, iOS */
       url('../fonts/open-sans-v18-latin-700.svg#OpenSans') format('svg'); /* Legacy iOS */
}

Now here's whats really weird... The fonts on the start page are rendered properly. But as soon as I click on the Strato project page, the fonts are rendered bold. I really don't understand why, because the strato project page uses the same module "text_groups".


Start page with local fonts installed
![start with local fonts installed](https://user-images.githubusercontent.com/29971407/118396906-eecdc100-b651-11eb-9077-1f221bf16a7b.png)

Project page with local fonts installed
![strato project wrong font](https://user-images.githubusercontent.com/29971407/118396862-c3e36d00-b651-11eb-8012-f2cd26117f26.png)

The funny thing is: This only happens in Safari and Mozilla; In chrome this issue doesn't appear. Maybe this helps...

I hope you understand what I mean.

Cheers,
Mark

**Comment by MUWalter** [comment]
Please find the modified page with the project page and the local installed fonts: 
[website standard.zip](https://github.com/serg/yourfolio/files/6489207/website.standard.zip)

**Comment by serg** [comment]
Hello Mark,
The [google-webfonts-helper](https://google-webfonts-helper.herokuapp.com/) is great tool for getting font files from Google. But we need to set the `Customize folder prefix` field as `/fonts/`, because all content inside `/static/` folder related to the root of website (e.g. https://domain.name/fonts/). Also I added `font-display: swap;` css rule for every font variant inside `_fonts.scss` for improving font loading.

Here is the content of `_fonts.scss` file:
```css
/* open-sans-regular - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url('/fonts/open-sans-v18-latin-regular.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/fonts/open-sans-v18-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/fonts/open-sans-v18-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
       url('/fonts/open-sans-v18-latin-regular.woff') format('woff'), /* Modern Browsers */
       url('/fonts/open-sans-v18-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/fonts/open-sans-v18-latin-regular.svg#OpenSans') format('svg'); /* Legacy iOS */
}
/* open-sans-600 - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 600;
  font-display: swap;
  src: url('/fonts/open-sans-v18-latin-600.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/fonts/open-sans-v18-latin-600.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/fonts/open-sans-v18-latin-600.woff2') format('woff2'), /* Super Modern Browsers */
       url('/fonts/open-sans-v18-latin-600.woff') format('woff'), /* Modern Browsers */
       url('/fonts/open-sans-v18-latin-600.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/fonts/open-sans-v18-latin-600.svg#OpenSans') format('svg'); /* Legacy iOS */
}
/* open-sans-700 - latin */
@font-face {
  font-family: 'Open Sans';
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url('/fonts/open-sans-v18-latin-700.eot'); /* IE9 Compat Modes */
  src: local(''),
       url('/fonts/open-sans-v18-latin-700.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('/fonts/open-sans-v18-latin-700.woff2') format('woff2'), /* Super Modern Browsers */
       url('/fonts/open-sans-v18-latin-700.woff') format('woff'), /* Modern Browsers */
       url('/fonts/open-sans-v18-latin-700.ttf') format('truetype'), /* Safari, Android, iOS */
       url('/fonts/open-sans-v18-latin-700.svg#OpenSans') format('svg'); /* Legacy iOS */
}
```
